AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3]
BATCH_SIZE: 32
INCLUDE_TOP: False
EPOCHS: 20
CLASSES: 3
WEIGHTS: imagenet
LEARNING_RATE: 0.0001
VALIDATION_SPLIT: 0.20  # Added for data transformation

# Configuration
# BATCH_SIZE = 32
# IMG_SIZE = (224, 224)
# INPUT_SHAPE = (224, 224, 3)
# EPOCHS = 15 
# LEARNING_RATE = 1e-4 