artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://www.kaggle.com/datasets/pacificrm/skindiseasedataset
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion/raw_extracted
  final_dataset_dir: artifacts/data_ingestion/dataset

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/dataset
  STATUS_FILE: artifacts/data_validation/status.txt
  all_classes:
    - Acne
    - Bullous
    - Actinic Keratosis
    - Benign Tumors
    - Candidiasis
    - Drug Eruption
    - Eczema
    - Infestations/Bites
    - Lichen
    - Lupus
    - Moles
    -  Psoriasis
    - Rosacea
    - Seborrheic Keratoses
    - Skin Cancer
    - Sun/Sunlight Damage
    - Tinea
    - Unknown/Normal
    - Vascular Tumors
    - Vasculitis
    - Vitiligo
    - Warts